### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by WennyLiang** [danylokos/LiveView#1]
I Run the project 【Build target LiveView-iOS】on Xcode 13.0 on a non-jailbroken iPhone ,but alway compile fail.

**Comment by danylokos** [comment]
It's not intended to be run on iOS device through Xcode, you can do it, but there is no point, it won't do anything. There is a "Run Script" step in the "Build Phase" (iOS target), which simply generates the ` deb` package that you can later install on jailbroken iPhone. 

The script fails because you are probably missing some of the utils, either `ldid` or `dpkg-deb`.

`brew install ldid dpkg`

**Comment by danylokos** [comment]
Also, you can download a pre-built package from [releases](https://github.com/danylokos/LiveView/releases/tag/v1.0.0).

**Comment by WennyLiang** [comment]
OK.Think you



At 2022-08-05 13:33:14, "Danylo Kostyshyn" ***@***.***> wrote:

Also, you can download a pre-built package form releases.
